import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = path.join(rootDir, 'site', 'data');
const jsonPath = path.join(dataDir, 'dice_tree.json');
const svgPath = path.join(dataDir, 'dice_tree.svg');
const dataJsPath = path.join(dataDir, 'tree_data.js');
const svgJsPath = path.join(dataDir, 'tree_svg.js');
const checkOnly = process.argv.includes('--check');

function normalize(value) {
  return value.replace(/\r\n/g, '\n');
}

const treeData = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const treeSvg = fs.readFileSync(svgPath, 'utf8').replace(/^\uFEFF/, '');
const generatedHeader = '/* Generated by scripts/sync_site_data.mjs. Do not edit directly. */\n';
const expectedDataJs = `${generatedHeader}window.TREE_DATA = ${JSON.stringify(treeData, null, 2)};\n`;
const expectedSvgJs = `${generatedHeader}window.DICE_TREE_SVG = window.__DICE_TREE_SVG__ = ${JSON.stringify(treeSvg)};\n`;

const expected = [
  [dataJsPath, expectedDataJs],
  [svgJsPath, expectedSvgJs],
];

const mismatches = [];
for (const [filePath, expectedText] of expected) {
  if (!fs.existsSync(filePath)) {
    mismatches.push(`${path.relative(rootDir, filePath)} is missing`);
    continue;
  }
  const actualText = normalize(fs.readFileSync(filePath, 'utf8'));
  if (actualText !== expectedText) {
    mismatches.push(`${path.relative(rootDir, filePath)} differs from its source data`);
  }
}

if (checkOnly) {
  if (mismatches.length > 0) {
    console.error(`Generated data check failed:\n- ${mismatches.join('\n- ')}\nRun: npm run generate:data`);
    process.exit(1);
  }
  console.log('Generated data is synchronized with site/data/dice_tree.json and site/data/dice_tree.svg.');
} else {
  fs.writeFileSync(dataJsPath, expectedDataJs, 'utf8');
  fs.writeFileSync(svgJsPath, expectedSvgJs, 'utf8');
  console.log('Generated tree_data.js and tree_svg.js from the canonical JSON/SVG sources.');
}
